### ISSUE TITLE
how to Serve private images using signed URL tokens

### ISSUE THREAD

**Issue by BeiAduo** [DeDmytro/laravel-cloudflare-images#10]
[[

### Description:
](https://developers.cloudflare.com/images/cloudflare-images/serve-images/serve-private-images-using-signed-url-tokens/)](https://developers.cloudflare.com/images/cloudflare-images/serve-images/serve-private-images-using-signed-url-tokens/)

**Comment by DeDmytro** [comment]
@BeiAduo , thanks for suggestion! it must be something new from Cloudflare Images. I'll check

**Comment by DeDmytro** [comment]
@BeiAduo , just released support for signed Url. Could you check by updating to the recent version ?
`"dedmytro/laravel-cloudflare-images": "^0.2"`
