### ISSUE TITLE
Meta tags

### ISSUE THREAD

**Issue by Rahul-codoffer** [DeDmytro/laravel-cloudflare-images#16]
How can we add the meta tags to image ?

**Comment by DeDmytro** [comment]
Have you tried to specify the `metadata` param for the `upload(` method:

```
CloudflareApi::images()->upload(
            $request->file('image'),
            metadata: ['my_tag' => 'my_value']
);
```

Then you can see your metadata on Cloudflare Dashboard

**Comment by DeDmytro** [comment]
I see the issue that metadata isn't returned with Image Response. I'll get it fixed

**Comment by DeDmytro** [comment]
That was fixed in https://github.com/DeDmytro/laravel-cloudflare-images/releases/tag/0.2.1
