### ISSUE TITLE
Guzzle 7 Support

### ISSUE THREAD

**Issue by robjbrain** [DeDmytro/laravel-cloudflare-images#2]
When running composer install i'm getting the following error:

dedmytro/laravel-cloudflare-images 0.1.5 requires guzzlehttp/guzzle ^6.2.1 -> found guzzlehttp/guzzle[6.2.1, ..., 6.5.x-dev] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Is it compatible with Guzzle 7?

**Comment by DeDmytro** [comment]
@robjbrain, thanks! Added support for Guzzle v ^7
https://github.com/DeDmytro/laravel-cloudflare-images/commit/5b0377e8660022420278a9b124b8312dfd2a1865
